---
- block:
    - name: Ensure service file copied
      template:
        src: "k3s.service.j2"
        dest: "/usr/lib/systemd/system/k3s-worker.service"
        owner: root
        group: root
        mode: 0644
      notify: "Ensure k3s-worker service reloaded, restarted and enabled"

    - name: Flush handlers
      meta: flush_handlers

