---
- hosts: fleet
  become: yes
  remote_user: root
  roles:
    - role: common

- hosts: masters
  become: yes
  remote_user: root
  roles:
    - role: k3s-master

- hosts: workers
  become: yes
  remote_user: root
  roles:
    - role: k3s-worker

