---
- block:
    - name: Ensure service file copied
      template:
        src: "k3s.service.j2"
        dest: "/usr/lib/systemd/system/k3s-master.service"
        owner: root
        group: root
        mode: 0644

    - name: Ensure service enabled
      systemd:
        name: k3s-master
        daemon_reload: yes
        state: restarted
        enabled: yes

    - name: Wait for node-token
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: Register node-token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set node-token fact
      set_fact:
        token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

    - name: Ensure kubectl symlink
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link

